
GET http://localhost:3000/


###
// register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "provaUser5343",
    "surname": "cognomeUser",
    "email": "provaUser5343@gmail.com",
    "password": "test123"
}

###
//login 
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "provaUser5343@gmail.com",
    "password": "test123"
}

###logout
GET http://localhost:3000/api/auth/logout

###
// show user info
GET http://localhost:3000/api/auth/user
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTI3ODY0MDUsImV4cCI6MTcxMjg3MjgwNX0.ukI4x7f982HmduembD5wUd0tNkKdWCFWiTtLHaNcE8s"