
GET http://localhost:3000/

###
// show cart 
GET http://localhost:3000/api/cart/

###
// add new product to cart
POST http://localhost:3000/api/cart/add/66165bd0ce5e23db9529385c
Content-Type: application/json

{
    "userId": "66144f37c750c125fda509fa"
}

// delete producut by id
###
DELETE  http://localhost:3000/api/cart/remove/66165bd0ce5e23db9529385c


// delete all product by cart
###
DELETE  http://localhost:3000/api/cart/clear
