
GET http://localhost:3000/

###
// show all product (no admin)
GET http://localhost:3000/api/products/

###
// add new product (user)
POST http://localhost:3000/api/products/
Content-Type: application/json

{
    "name": "fantastic product",
    "brand": "Dream Brands Inc.",
    "quantity": 40,
    "price": 49.99,
    "sale": 0.2
}

###
// get product by id
GET http://localhost:3000/api/products/66165bdace5e23db9529385e


// delete producut by id
###
DELETE  http://localhost:3000/api/products/66165bdace5e23db9529385e


// aggiorna product by id 
###
PUT http://localhost:3000/api/products/661505b33fdb4d3ae1fc7995
Content-Type: application/json

{
    "id": "321",
    "name": "Fantasy Product fabio",
    "brand": "Dream Brands Inc.",
    "quantity": 80,
    "price": 99.99,
    "sale": 0.2
}